apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  capacity:
    storage: 256Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/data/mongo"  # Ensure this path exists on the node

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pv-claim  # Name of the PVC
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
  storageClassName: manual  # Must match the PV storageClass

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-depy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-pod
  template:
    metadata:
      labels:
        app: mongo-pod
    spec:
      containers:
        - image: mongo:4.4
          name: mongo-container
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
      volumes:
        - name: mongo-persistent-storage
          persistentVolumeClaim:
            claimName: mongo-pv-claim  # Reference the PVC name

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-srv
spec:
  ports:
    - port: 27017
      
  selector:
    app: mongo-pod
    
  type: ClusterIP
